version: "2"

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - revive
    - gocyclo
    - misspell
    - unused
  settings:
    gocyclo:
      min-complexity: 15

formatters:
  enable:
    - gofumpt
