// The Tier 2 module contract: a module in its own process, speaking to the app over gRPC.
// Each service method and message mirrors a Tier 1 method or type in mindseye/pkg/sdk.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: mindseye/module/v1/module.proto

package modulev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusLevel int32

const (
	StatusLevel_STATUS_LEVEL_UNKNOWN StatusLevel = 0
	StatusLevel_STATUS_LEVEL_OK      StatusLevel = 1
	StatusLevel_STATUS_LEVEL_WARN    StatusLevel = 2
	StatusLevel_STATUS_LEVEL_CRIT    StatusLevel = 3
	StatusLevel_STATUS_LEVEL_DOWN    StatusLevel = 4
)

// Enum value maps for StatusLevel.
var (
	StatusLevel_name = map[int32]string{
		0: "STATUS_LEVEL_UNKNOWN",
		1: "STATUS_LEVEL_OK",
		2: "STATUS_LEVEL_WARN",
		3: "STATUS_LEVEL_CRIT",
		4: "STATUS_LEVEL_DOWN",
	}
	StatusLevel_value = map[string]int32{
		"STATUS_LEVEL_UNKNOWN": 0,
		"STATUS_LEVEL_OK":      1,
		"STATUS_LEVEL_WARN":    2,
		"STATUS_LEVEL_CRIT":    3,
		"STATUS_LEVEL_DOWN":    4,
	}
)

func (x StatusLevel) Enum() *StatusLevel {
	p := new(StatusLevel)
	*p = x
	return p
}

func (x StatusLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_mindseye_module_v1_module_proto_enumTypes[0].Descriptor()
}

func (StatusLevel) Type() protoreflect.EnumType {
	return &file_mindseye_module_v1_module_proto_enumTypes[0]
}

func (x StatusLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusLevel.Descriptor instead.
func (StatusLevel) EnumDescriptor() ([]byte, []int) {
	return file_mindseye_module_v1_module_proto_rawDescGZIP(), []int{0}
}

type Severity int32

const (
	Severity_SEVERITY_DEBUG    Severity = 0
	Severity_SEVERITY_INFO     Severity = 1
	Severity_SEVERITY_WARN     Severity = 2
	Severity_SEVERITY_ERROR    Severity = 3
	Severity_SEVERITY_CRITICAL Severity = 4
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "SEVERITY_DEBUG",
		1: "SEVERITY_INFO",
		2: "SEVERITY_WARN",
		3: "SEVERITY_ERROR",
		4: "SEVERITY_CRITICAL",
	}
	Severity_value = map[string]int32{
		"SEVERITY_DEBUG":    0,
		"SEVERITY_INFO":     1,
		"SEVERITY_WARN":     2,
		"SEVERITY_ERROR":    3,
		"SEVERITY_CRITICAL": 4,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_mindseye_module_v1_module_proto_enumTypes[1].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_mindseye_module_v1_module_proto_enumTypes[1]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_mindseye_module_v1_module_proto_rawDescGZIP(), []int{1}
}

type Aggregation int32

const (
	Aggregation_AGGREGATION_NONE Aggregation = 0
	Aggregation_AGGREGATION_AVG  Aggregation = 1
	Aggregation_AGGREGATION_MAX  Aggregation = 2
	Aggregation_AGGREGATION_MIN  Aggregation = 3
	Aggregation_AGGREGATION_SUM  Aggregation = 4
	Aggregation_AGGREGATION_P95  Aggregation = 5
)

// Enum value maps for Aggregation.
var (
	Aggregation_name = map[int32]string{
		0: "AGGREGATION_NONE",
		1: "AGGREGATION_AVG",
		2: "AGGREGATION_MAX",
		3: "AGGREGATION_MIN",
		4: "AGGREGATION_SUM",
		5: "AGGREGATION_P95",
	}
	Aggregation_value = map[string]int32{
		"AGGREGATION_NONE": 0,
		"AGGREGATION_AVG":  1,
		"AGGREGATION_MAX":  2,
		"AGGREGATION_MIN":  3,
		"AGGREGATION_SUM":  4,
		"AGGREGATION_P95":  5,
	}
)

func (x Aggregation) Enum() *Aggregation {
	p := new(Aggregation)
	*p = x
	return p
}

func (x Aggregation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Aggregation) Descriptor() protoreflect.EnumDescriptor {
	return file_mindseye_module_v1_module_proto_enumTypes[2].Descriptor()
}

func (Aggregation) Type() protoreflect.EnumType {
	return &file_mindseye_module_v1_module_proto_enumTypes[2]
}

func (x Aggregation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Aggregation.Descriptor instead.
func (Aggregation) EnumDescriptor() ([]byte, []int) {
	return file_mindseye_module_v1_module_proto_rawDescGZIP(), []int{2}
}

// Version is the contract's version: a major change breaks compatibility, a minor one adds.
type Version struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Major         uint32                 `protobuf:"varint,1,opt,name=major,proto3" json:"major,omitempty"`
	Minor         uint32                 `protobuf:"varint,2,opt,name=minor,proto3" json:"minor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Version) Reset() {
	*x = Version{}
	mi := &file_mindseye_module_v1_module_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version) ProtoMessage() {}

func (x *Version) ProtoReflect() protoreflect.Message {
	mi := &file_mindseye_module_v1_module_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version.ProtoReflect.Descriptor instead.
func (*Version) Descriptor() ([]byte, []int) {
	return file_mindseye_module_v1_module_proto_rawDescGZIP(), []int{0}
}

func (x *Version) GetMajor() uint32 {
	if x != nil {
		return x.Major
	}
	return 0
}

func (x *Version) GetMinor() uint32 {
	if x != nil {
		return x.Minor
	}
	return 0
}

type InfoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The version the app speaks.
	Host          *Version `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_mindseye_module_v1_module_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mindseye_module_v1_module_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_mindseye_module_v1_module_proto_rawDescGZIP(), []int{1}
}

func (x *InfoRequest) GetHost() *Version {
	if x != nil {
		return x.Host
	}
	return nil
}

type InfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The version the module speaks.
	Module      *Version `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Kind        string   `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Version     string   `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Description string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Optional methods implemented: discover, series, events, subscribe, search.
	Capabilities  []string `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_mindseye_module_v1_module_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mindseye_module_v1_module_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_mindseye_module_v1_module_proto_rawDescGZIP(), []int{2}
}

func (x *InfoResponse) GetModule() *Version {
	if x != nil {
		return x.Module
	}
	return nil
}

func (x *InfoResponse) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *InfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InfoResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *InfoResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type ConfigureRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The line of the module's entry in the config file.
	Line int32 `protobuf:"varint,2,opt,name=line,proto3" json:"line,omitempty"`
	// The entry's options, absent when it has none.
	Options       *YamlNode `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	mi := &file_mindseye_module_v1_module_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mindseye_module_v1_module_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return file_mindseye_module_v1_module_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigureRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConfigureRequest) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *ConfigureRequest) GetOptions() *YamlNode {
	if x != nil {
		return x.Options
	}
	return nil
}

type ConfigureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureResponse) Reset() {
	*x = ConfigureResponse{}
	mi := &file_mindseye_module_v1_module_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureResponse) ProtoMessage() {}

func (x *ConfigureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mindseye_module_v1_module_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureResponse.ProtoReflect.Descriptor instead.
func (*ConfigureResponse) Descriptor() ([]byte, []int) {
	return file_mindseye_module_v1_module_proto_rawDescGZIP(), []int{4}
}

// YamlNode is a parsed YAML node, with its position in the config file for error messages.
type YamlNode struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Kind   uint32                 `protobuf:"varint,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Style  uint32                 `protobuf:"varint,2,opt,name=style,proto3" json:"style,omitempty"`
	Tag    string                 `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	Value  string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Anchor string                 `protobuf:"bytes,5,opt,name=anchor,proto3" json:"anchor,omitempty"`
	Line   int32                  `protobuf:"varint,6,opt,name=line,proto3" json:"line,omitempty"`
	Column int32                  `protobuf:"varint,7,opt,name=column,proto3" json:"column,omitempty"`
	// Children; an alias node has one, the node it refers to.
	Content       []*YamlNode `protobuf:"bytes,8,rep,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YamlNode) Reset() {
	*x = YamlNode{}
	mi := &file_mindseye_module_v1_module_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YamlNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YamlNode) ProtoMessage() {}

func (x *YamlNode) ProtoReflect() protoreflect.Message {
	mi := &file_mindseye_module_v1_module_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YamlNode.ProtoReflect.Descriptor instead.
func (*YamlNode) Descriptor() ([]byte, []int) {
	return file_mindseye_module_v1_module_proto_rawDescGZIP(), []int{5}
}

func (x *YamlNode) GetKind() uint32 {
	if x != nil {
		return x.Kind
	}
	return 0
}

func (x *YamlNode) GetStyle() uint32 {
	if x != nil {
		return x.Style
	}
	return 0
}

func (x *YamlNode) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *YamlNode) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *YamlNode) GetAnchor() string {
	if x != nil {
		return x.Anchor
	}
	return ""
}

func (x *YamlNode) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *YamlNode) GetColumn() int32 {
	if x != nil {
		return x.Column
	}
	return 0
}

func (x *YamlNode) GetContent() []*YamlNode {
	if x != nil {
		return x.Content
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_mindseye_module_v1_module_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mindseye_module_v1_module_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_mindseye_module_v1_module_proto_rawDescGZIP(), []int{6}
}

type HealthResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Disconnected bool                   `protobuf:"varint,1,opt,name=disconnected,proto3" json:"disconnected,omitempty"`
	// The error's message, absent when there is none.
	Error         *string `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	Note          string  `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_mindseye_module_v1_module_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mindseye_module_v1_module_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_mindseye_module_v1_module_proto_rawDescGZIP(), []int{7}
}

func (x *HealthResponse) GetDisconnected() bool {
	if x != nil {
		return x.Disconnected
	}
	return false
}

func (x *HealthResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *HealthResponse) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type RunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_mindseye_module_v1_module_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mindseye_module_v1_module_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_mindseye_module_v1_module_proto_rawDescGZIP(), []int{8}
}

// RunResponse is one part of a change set; a large one is sent in parts, joined in order.
type RunResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The change set replaces everything the module sent before.
	Snapshot  bool       `protobuf:"varint,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	ChangeSet *ChangeSet `protobuf:"bytes,2,opt,name=change_set,json=changeSet,proto3" json:"change_set,omitempty"`
	// More parts of this change set follow.
	Continued     bool `protobuf:"varint,3,opt,name=continued,proto3" json:"continued,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunResponse) Reset() {
	*x = RunResponse{}
	mi := &file_mindseye_module_v1_module_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResponse) ProtoMessage() {}

func (x *RunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mindseye_module_v1_module_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResponse.ProtoReflect.Descriptor instead.
func (*RunResponse) Descriptor() ([]byte, []int) {
	return file_mindseye_module_v1_module_proto_rawDescGZIP(), []int{9}
}

func (x *RunResponse) GetSnapshot() bool {
	if x != nil {
		return x.Snapshot
	}
	return false
}

func (x *RunResponse) GetChangeSet() *ChangeSet {
	if x != nil {
		return x.ChangeSet
	}
	return nil
}

func (x *RunResponse) GetContinued() bool {
	if x != nil {
		return x.Continued
	}
	return false
}

type DiscoverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverRequest) Reset() {
	*x = DiscoverRequest{}
	mi := &file_mindseye_module_v1_module_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverRequest) ProtoMessage() {}

func (x *DiscoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mindseye_module_v1_module_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverRequest.ProtoReflect.Descriptor instead.
func (*DiscoverRequest) Descriptor() ([]byte, []int) {
	return file_mindseye_module_v1_module_proto_rawDescGZIP(), []int{10}
}

type DiscoverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChangeSet     *ChangeSet             `protobuf:"bytes,1,opt,name=change_set,json=changeSet,proto3" json:"change_set,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverResponse) Reset() {
	*x = DiscoverResponse{}
	mi := &file_mindseye_module_v1_module_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverResponse) ProtoMessage() {}

func (x *DiscoverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mindseye_module_v1_module_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverResponse.ProtoReflect.Descriptor instead.
func (*DiscoverResponse) Descriptor() ([]byte, []int) {
	return file_mindseye_module_v1_module_proto_rawDescGZIP(), []int{11}
}

func (x *DiscoverResponse) GetChangeSet() *ChangeSet {
	if x != nil {
		return x.ChangeSet
	}
	return nil
}

type MetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsRequest) Reset() {
	*x = MetricsRequest{}
	mi := &file_mindseye_module_v1_module_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRequest) ProtoMessage() {}

func (x *MetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mindseye_module_v1_module_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRequest.ProtoReflect.Descriptor instead.
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return file_mindseye_module_v1_module_proto_rawDescGZIP(), []int{12}
}

type MetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*Metric              `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_mindseye_module_v1_module_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mindseye_module_v1_module_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_mindseye_module_v1_module_proto_rawDescGZIP(), []int{13}
}

func (x *MetricsResponse) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type QuerySeriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         *SeriesQuery           `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuerySeriesRequest) Reset() {
	*x = QuerySeriesRequest{}
	mi := &file_mindseye_module_v1_module_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuerySeriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuerySeriesRequest) ProtoMessage() {}

func (x *QuerySeriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mindseye_module_v1_module_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuerySeriesRequest.ProtoReflect.Descriptor instead.
func (*QuerySeriesRequest) Descriptor() ([]byte, []int) {
	return file_mindseye_module_v1_module_proto_rawDescGZIP(), []int{14}
}

func (x *QuerySeriesRequest) GetQuery() *SeriesQuery {
	if x != nil {
		return x.Query
	}
	return nil
}

type QuerySeriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Series        []*Series              `protobuf:"bytes,1,rep,name=series,proto3" json:"series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuerySeriesResponse) Reset() {
	*x = QuerySeriesResponse{}
	mi := &file_mindseye_module_v1_module_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuerySeriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuerySeriesResponse) ProtoMessage() {}

func (x *QuerySeriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mindseye_module_v1_module_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuerySeriesResponse.ProtoReflect.Descriptor instead.
func (*QuerySeriesResponse) Descriptor() ([]byte, []int) {
	return file_mindseye_module_v1_module_proto_rawDescGZIP(), []int{15}
}

func (x *QuerySeriesResponse) GetSeries() []*Series {
	if x != nil {
		return x.Series
	}
	return nil
}

type QueryEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         *EventQuery            `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryEventsRequest) Reset() {
	*x = QueryEventsRequest{}
	mi := &file_mindseye_module_v1_module_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryEventsRequest) ProtoMessage() {}

func (x *QueryEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mindseye_module_v1_module_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryEventsRequest.ProtoReflect.Descriptor instead.
func (*QueryEventsRequest) Descriptor() ([]byte, []int) {
	return file_mindseye_module_v1_module_proto_rawDescGZIP(), []int{16}
}

func (x *QueryEventsRequest) GetQuery() *EventQuery {
	if x != nil {
		return x.Query
	}
	return nil
}

type QueryEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryEventsResponse) Reset() {
	*x = QueryEventsResponse{}
	mi := &file_mindseye_module_v1_module_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryEventsResponse) ProtoMessage() {}

func (x *QueryEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mindseye_module_v1_module_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryEventsResponse.ProtoReflect.Descriptor instead.
func (*QueryEventsResponse) Descriptor() ([]byte, []int) {
	return file_mindseye_module_v1_module_proto_rawDescGZIP(), []int{17}
}

func (x *QueryEventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         *SeriesQuery           `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_mindseye_module_v1_module_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mindseye_module_v1_module_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_mindseye_module_v1_module_proto_rawDescGZIP(), []int{18}
}

func (x *SubscribeRequest) GetQuery() *SeriesQuery {
	if x != nil {
		return x.Query
	}
	return nil
}

type SubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Series        []*Series              `protobuf:"bytes,1,rep,name=series,proto3" json:"series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_mindseye_module_v1_module_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mindseye_module_v1_module_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_mindseye_module_v1_module_proto_rawDescGZIP(), []int{19}
}

func (x *SubscribeResponse) GetSeries() []*Series {
	if x != nil {
		return x.Series
	}
	return nil
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_mindseye_module_v1_module_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mindseye_module_v1_module_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_mindseye_module_v1_module_proto_rawDescGZIP(), []int{20}
}

func (x *SearchRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Entity refs, best match first.
	Refs          []string `protobuf:"bytes,1,rep,name=refs,proto3" json:"refs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_mindseye_module_v1_module_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mindseye_module_v1_module_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_mindseye_module_v1_module_proto_rawDescGZIP(), []int{21}
}

func (x *SearchResponse) GetRefs() []string {
	if x != nil {
		return x.Refs
	}
	return nil
}

// ChangeSet is applied in field order: removals, edge removals, upserts, edges, events.
type ChangeSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Removes       []string               `protobuf:"bytes,1,rep,name=removes,proto3" json:"removes,omitempty"`
	RemoveEdges   []*EdgeKey             `protobuf:"bytes,2,rep,name=remove_edges,json=removeEdges,proto3" json:"remove_edges,omitempty"`
	Upserts       []*Entity              `protobuf:"bytes,3,rep,name=upserts,proto3" json:"upserts,omitempty"`
	Edges         []*Edge                `protobuf:"bytes,4,rep,name=edges,proto3" json:"edges,omitempty"`
	Events        []*Event               `protobuf:"bytes,5,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeSet) Reset() {
	*x = ChangeSet{}
	mi := &file_mindseye_module_v1_module_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeSet) ProtoMessage() {}

func (x *ChangeSet) ProtoReflect() protoreflect.Message {
	mi := &file_mindseye_module_v1_module_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeSet.ProtoReflect.Descriptor instead.
func (*ChangeSet) Descriptor() ([]byte, []int) {
	return file_mindseye_module_v1_module_proto_rawDescGZIP(), []int{22}
}

func (x *ChangeSet) GetRemoves() []string {
	if x != nil {
		return x.Removes
	}
	return nil
}

func (x *ChangeSet) GetRemoveEdges() []*EdgeKey {
	if x != nil {
		return x.RemoveEdges
	}
	return nil
}

func (x *ChangeSet) GetUpserts() []*Entity {
	if x != nil {
		return x.Upserts
	}
	return nil
}

func (x *ChangeSet) GetEdges() []*Edge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *ChangeSet) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type Entity struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Ref    string                 `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Kind   string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Name   string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Attrs  map[string]*Value      `protobuf:"bytes,4,rep,name=attrs,proto3" json:"attrs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Status StatusLevel            `protobuf:"varint,5,opt,name=status,proto3,enum=mindseye.module.v1.StatusLevel" json:"status,omitempty"`
	Reason string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	Tags   []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	Source string                 `protobuf:"bytes,8,opt,name=source,proto3" json:"source,omitempty"`
	// Unix nanoseconds; absent for the zero time.
	Seen          *int64 `protobuf:"zigzag64,9,opt,name=seen,proto3,oneof" json:"seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_mindseye_module_v1_module_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_mindseye_module_v1_module_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_mindseye_module_v1_module_proto_rawDescGZIP(), []int{23}
}

func (x *Entity) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *Entity) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Entity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Entity) GetAttrs() map[string]*Value {
	if x != nil {
		return x.Attrs
	}
	return nil
}

func (x *Entity) GetStatus() StatusLevel {
	if x != nil {
		return x.Status
	}
	return StatusLevel_STATUS_LEVEL_UNKNOWN
}

func (x *Entity) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Entity) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Entity) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Entity) GetSeen() int64 {
	if x != nil && x.Seen != nil {
		return *x.Seen
	}
	return 0
}

type EdgeKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Rel           string                 `protobuf:"bytes,3,opt,name=rel,proto3" json:"rel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgeKey) Reset() {
	*x = EdgeKey{}
	mi := &file_mindseye_module_v1_module_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeKey) ProtoMessage() {}

func (x *EdgeKey) ProtoReflect() protoreflect.Message {
	mi := &file_mindseye_module_v1_module_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeKey.ProtoReflect.Descriptor instead.
func (*EdgeKey) Descriptor() ([]byte, []int) {
	return file_mindseye_module_v1_module_proto_rawDescGZIP(), []int{24}
}

func (x *EdgeKey) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *EdgeKey) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *EdgeKey) GetRel() string {
	if x != nil {
		return x.Rel
	}
	return ""
}

type Edge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Rel           string                 `protobuf:"bytes,3,opt,name=rel,proto3" json:"rel,omitempty"`
	Weight        float64                `protobuf:"fixed64,4,opt,name=weight,proto3" json:"weight,omitempty"`
	Attrs         map[string]*Value      `protobuf:"bytes,5,rep,name=attrs,proto3" json:"attrs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Source        string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Edge) Reset() {
	*x = Edge{}
	mi := &file_mindseye_module_v1_module_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_mindseye_module_v1_module_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_mindseye_module_v1_module_proto_rawDescGZIP(), []int{25}
}

func (x *Edge) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Edge) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Edge) GetRel() string {
	if x != nil {
		return x.Rel
	}
	return ""
}

func (x *Edge) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Edge) GetAttrs() map[string]*Value {
	if x != nil {
		return x.Attrs
	}
	return nil
}

func (x *Edge) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Empty for an event about no entity.
	Entity string `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"`
	// Unix nanoseconds; absent for the zero time.
	At            *int64            `protobuf:"zigzag64,3,opt,name=at,proto3,oneof" json:"at,omitempty"`
	Severity      Severity          `protobuf:"varint,4,opt,name=severity,proto3,enum=mindseye.module.v1.Severity" json:"severity,omitempty"`
	Kind          string            `protobuf:"bytes,5,opt,name=kind,proto3" json:"kind,omitempty"`
	Message       string            `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	Fields        map[string]*Value `protobuf:"bytes,7,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Source        string            `protobuf:"bytes,8,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_mindseye_module_v1_module_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_mindseye_module_v1_module_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_mindseye_module_v1_module_proto_rawDescGZIP(), []int{26}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *Event) GetAt() int64 {
	if x != nil && x.At != nil {
		return *x.At
	}
	return 0
}

func (x *Event) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_DEBUG
}

func (x *Event) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Event) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Event) GetFields() map[string]*Value {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Event) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// Value is an attribute's value; none is set for an empty value.
type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*Value_StringValue
	//	*Value_NumberValue
	//	*Value_BoolValue
	//	*Value_TimeValue
	//	*Value_ListValue
	Value         isValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_mindseye_module_v1_module_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_mindseye_module_v1_module_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_mindseye_module_v1_module_proto_rawDescGZIP(), []int{27}
}

func (x *Value) GetValue() isValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Value) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*Value_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Value) GetNumberValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*Value_NumberValue); ok {
			return x.NumberValue
		}
	}
	return 0
}

func (x *Value) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*Value_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *Value) GetTimeValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*Value_TimeValue); ok {
			return x.TimeValue
		}
	}
	return 0
}

func (x *Value) GetListValue() *ValueList {
	if x != nil {
		if x, ok := x.Value.(*Value_ListValue); ok {
			return x.ListValue
		}
	}
	return nil
}

type isValue_Value interface {
	isValue_Value()
}

type Value_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Value_NumberValue struct {
	NumberValue float64 `protobuf:"fixed64,2,opt,name=number_value,json=numberValue,proto3,oneof"`
}

type Value_BoolValue struct {
	BoolValue bool `protobuf:"varint,3,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type Value_TimeValue struct {
	// Unix nanoseconds.
	TimeValue int64 `protobuf:"zigzag64,4,opt,name=time_value,json=timeValue,proto3,oneof"`
}

type Value_ListValue struct {
	ListValue *ValueList `protobuf:"bytes,5,opt,name=list_value,json=listValue,proto3,oneof"`
}

func (*Value_StringValue) isValue_Value() {}

func (*Value_NumberValue) isValue_Value() {}

func (*Value_BoolValue) isValue_Value() {}

func (*Value_TimeValue) isValue_Value() {}

func (*Value_ListValue) isValue_Value() {}

type ValueList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*Value               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueList) Reset() {
	*x = ValueList{}
	mi := &file_mindseye_module_v1_module_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueList) ProtoMessage() {}

func (x *ValueList) ProtoReflect() protoreflect.Message {
	mi := &file_mindseye_module_v1_module_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueList.ProtoReflect.Descriptor instead.
func (*ValueList) Descriptor() ([]byte, []int) {
	return file_mindseye_module_v1_module_proto_rawDescGZIP(), []int{28}
}

func (x *ValueList) GetValues() []*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

type Metric struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Unit        string                 `protobuf:"bytes,2,opt,name=unit,proto3" json:"unit,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Entity kinds that have the metric; empty means any.
	Kinds []string `protobuf:"bytes,4,rep,name=kinds,proto3" json:"kinds,omitempty"`
	// The module's own expression.
	Native string `protobuf:"bytes,5,opt,name=native,proto3" json:"native,omitempty"`
	// Chosen by name rather than opened with its entity.
	Extra         bool `protobuf:"varint,6,opt,name=extra,proto3" json:"extra,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_mindseye_module_v1_module_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_mindseye_module_v1_module_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_mindseye_module_v1_module_proto_rawDescGZIP(), []int{29}
}

func (x *Metric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metric) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *Metric) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Metric) GetKinds() []string {
	if x != nil {
		return x.Kinds
	}
	return nil
}

func (x *Metric) GetNative() string {
	if x != nil {
		return x.Native
	}
	return ""
}

func (x *Metric) GetExtra() bool {
	if x != nil {
		return x.Extra
	}
	return false
}

type TimeWindow struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unix nanoseconds; absent for the zero time.
	From          *int64 `protobuf:"zigzag64,1,opt,name=from,proto3,oneof" json:"from,omitempty"`
	To            *int64 `protobuf:"zigzag64,2,opt,name=to,proto3,oneof" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeWindow) Reset() {
	*x = TimeWindow{}
	mi := &file_mindseye_module_v1_module_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeWindow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeWindow) ProtoMessage() {}

func (x *TimeWindow) ProtoReflect() protoreflect.Message {
	mi := &file_mindseye_module_v1_module_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeWindow.ProtoReflect.Descriptor instead.
func (*TimeWindow) Descriptor() ([]byte, []int) {
	return file_mindseye_module_v1_module_proto_rawDescGZIP(), []int{30}
}

func (x *TimeWindow) GetFrom() int64 {
	if x != nil && x.From != nil {
		return *x.From
	}
	return 0
}

func (x *TimeWindow) GetTo() int64 {
	if x != nil && x.To != nil {
		return *x.To
	}
	return 0
}

type SeriesQuery struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Explicit entity refs; otherwise the filter selects them.
	Entities []string    `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	Filter   *Filter     `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	Metrics  []string    `protobuf:"bytes,3,rep,name=metrics,proto3" json:"metrics,omitempty"`
	Window   *TimeWindow `protobuf:"bytes,4,opt,name=window,proto3" json:"window,omitempty"`
	// Resolution hint, in nanoseconds.
	Step int64       `protobuf:"varint,5,opt,name=step,proto3" json:"step,omitempty"`
	Agg  Aggregation `protobuf:"varint,6,opt,name=agg,proto3,enum=mindseye.module.v1.Aggregation" json:"agg,omitempty"`
	// The module's own query language, for power users.
	Native        string `protobuf:"bytes,7,opt,name=native,proto3" json:"native,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeriesQuery) Reset() {
	*x = SeriesQuery{}
	mi := &file_mindseye_module_v1_module_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeriesQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeriesQuery) ProtoMessage() {}

func (x *SeriesQuery) ProtoReflect() protoreflect.Message {
	mi := &file_mindseye_module_v1_module_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeriesQuery.ProtoReflect.Descriptor instead.
func (*SeriesQuery) Descriptor() ([]byte, []int) {
	return file_mindseye_module_v1_module_proto_rawDescGZIP(), []int{31}
}

func (x *SeriesQuery) GetEntities() []string {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *SeriesQuery) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *SeriesQuery) GetMetrics() []string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *SeriesQuery) GetWindow() *TimeWindow {
	if x != nil {
		return x.Window
	}
	return nil
}

func (x *SeriesQuery) GetStep() int64 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *SeriesQuery) GetAgg() Aggregation {
	if x != nil {
		return x.Agg
	}
	return Aggregation_AGGREGATION_NONE
}

func (x *SeriesQuery) GetNative() string {
	if x != nil {
		return x.Native
	}
	return ""
}

// Filter selects entities as the palette's filter syntax does.
type Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kinds         []string               `protobuf:"bytes,1,rep,name=kinds,proto3" json:"kinds,omitempty"`
	Sources       []string               `protobuf:"bytes,2,rep,name=sources,proto3" json:"sources,omitempty"`
	Statuses      []StatusLevel          `protobuf:"varint,3,rep,packed,name=statuses,proto3,enum=mindseye.module.v1.StatusLevel" json:"statuses,omitempty"`
	Metrics       []string               `protobuf:"bytes,4,rep,name=metrics,proto3" json:"metrics,omitempty"`
	SameAs        []string               `protobuf:"bytes,5,rep,name=same_as,json=sameAs,proto3" json:"same_as,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Attrs         []*Predicate           `protobuf:"bytes,7,rep,name=attrs,proto3" json:"attrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_mindseye_module_v1_module_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_mindseye_module_v1_module_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_mindseye_module_v1_module_proto_rawDescGZIP(), []int{32}
}

func (x *Filter) GetKinds() []string {
	if x != nil {
		return x.Kinds
	}
	return nil
}

func (x *Filter) GetSources() []string {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *Filter) GetStatuses() []StatusLevel {
	if x != nil {
		return x.Statuses
	}
	return nil
}

func (x *Filter) GetMetrics() []string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *Filter) GetSameAs() []string {
	if x != nil {
		return x.SameAs
	}
	return nil
}

func (x *Filter) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Filter) GetAttrs() []*Predicate {
	if x != nil {
		return x.Attrs
	}
	return nil
}

type Predicate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// One of = != < <= > >= ~ has.
	Op            string `protobuf:"bytes,2,opt,name=op,proto3" json:"op,omitempty"`
	Value         string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Predicate) Reset() {
	*x = Predicate{}
	mi := &file_mindseye_module_v1_module_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Predicate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Predicate) ProtoMessage() {}

func (x *Predicate) ProtoReflect() protoreflect.Message {
	mi := &file_mindseye_module_v1_module_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Predicate.ProtoReflect.Descriptor instead.
func (*Predicate) Descriptor() ([]byte, []int) {
	return file_mindseye_module_v1_module_proto_rawDescGZIP(), []int{33}
}

func (x *Predicate) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Predicate) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *Predicate) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SeriesRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entity        string                 `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	Metric        string                 `protobuf:"bytes,2,opt,name=metric,proto3" json:"metric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeriesRef) Reset() {
	*x = SeriesRef{}
	mi := &file_mindseye_module_v1_module_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeriesRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeriesRef) ProtoMessage() {}

func (x *SeriesRef) ProtoReflect() protoreflect.Message {
	mi := &file_mindseye_module_v1_module_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeriesRef.ProtoReflect.Descriptor instead.
func (*SeriesRef) Descriptor() ([]byte, []int) {
	return file_mindseye_module_v1_module_proto_rawDescGZIP(), []int{34}
}

func (x *SeriesRef) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *SeriesRef) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

// Series holds its points as two columns of equal length, in time order.
type Series struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Ref   *SeriesRef             `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Unit  string                 `protobuf:"bytes,2,opt,name=unit,proto3" json:"unit,omitempty"`
	// Unix nanoseconds.
	Times         []int64   `protobuf:"zigzag64,3,rep,packed,name=times,proto3" json:"times,omitempty"`
	Values        []float64 `protobuf:"fixed64,4,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Series) Reset() {
	*x = Series{}
	mi := &file_mindseye_module_v1_module_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Series) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Series) ProtoMessage() {}

func (x *Series) ProtoReflect() protoreflect.Message {
	mi := &file_mindseye_module_v1_module_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Series.ProtoReflect.Descriptor instead.
func (*Series) Descriptor() ([]byte, []int) {
	return file_mindseye_module_v1_module_proto_rawDescGZIP(), []int{35}
}

func (x *Series) GetRef() *SeriesRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *Series) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *Series) GetTimes() []int64 {
	if x != nil {
		return x.Times
	}
	return nil
}

func (x *Series) GetValues() []float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

type EventQuery struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Entities    []string               `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	Window      *TimeWindow            `protobuf:"bytes,2,opt,name=window,proto3" json:"window,omitempty"`
	MinSeverity Severity               `protobuf:"varint,3,opt,name=min_severity,json=minSeverity,proto3,enum=mindseye.module.v1.Severity" json:"min_severity,omitempty"`
	Kinds       []string               `protobuf:"bytes,4,rep,name=kinds,proto3" json:"kinds,omitempty"`
	// Most recent first when set.
	Limit         int32 `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventQuery) Reset() {
	*x = EventQuery{}
	mi := &file_mindseye_module_v1_module_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventQuery) ProtoMessage() {}

func (x *EventQuery) ProtoReflect() protoreflect.Message {
	mi := &file_mindseye_module_v1_module_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventQuery.ProtoReflect.Descriptor instead.
func (*EventQuery) Descriptor() ([]byte, []int) {
	return file_mindseye_module_v1_module_proto_rawDescGZIP(), []int{36}
}

func (x *EventQuery) GetEntities() []string {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *EventQuery) GetWindow() *TimeWindow {
	if x != nil {
		return x.Window
	}
	return nil
}

func (x *EventQuery) GetMinSeverity() Severity {
	if x != nil {
		return x.MinSeverity
	}
	return Severity_SEVERITY_DEBUG
}

func (x *EventQuery) GetKinds() []string {
	if x != nil {
		return x.Kinds
	}
	return nil
}

func (x *EventQuery) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_mindseye_module_v1_module_proto protoreflect.FileDescriptor

const file_mindseye_module_v1_module_proto_rawDesc = "" +
	"\n" +
	"\x1fmindseye/module/v1/module.proto\x12\x12mindseye.module.v1\"5\n" +
	"\aVersion\x12\x14\n" +
	"\x05major\x18\x01 \x01(\rR\x05major\x12\x14\n" +
	"\x05minor\x18\x02 \x01(\rR\x05minor\">\n" +
	"\vInfoRequest\x12/\n" +
	"\x04host\x18\x01 \x01(\v2\x1b.mindseye.module.v1.VersionR\x04host\"\xb7\x01\n" +
	"\fInfoResponse\x123\n" +
	"\x06module\x18\x01 \x01(\v2\x1b.mindseye.module.v1.VersionR\x06module\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\"\n" +
	"\fcapabilities\x18\x05 \x03(\tR\fcapabilities\"r\n" +
	"\x10ConfigureRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04line\x18\x02 \x01(\x05R\x04line\x126\n" +
	"\aoptions\x18\x03 \x01(\v2\x1c.mindseye.module.v1.YamlNodeR\aoptions\"\x13\n" +
	"\x11ConfigureResponse\"\xd8\x01\n" +
	"\bYamlNode\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\rR\x04kind\x12\x14\n" +
	"\x05style\x18\x02 \x01(\rR\x05style\x12\x10\n" +
	"\x03tag\x18\x03 \x01(\tR\x03tag\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12\x16\n" +
	"\x06anchor\x18\x05 \x01(\tR\x06anchor\x12\x12\n" +
	"\x04line\x18\x06 \x01(\x05R\x04line\x12\x16\n" +
	"\x06column\x18\a \x01(\x05R\x06column\x126\n" +
	"\acontent\x18\b \x03(\v2\x1c.mindseye.module.v1.YamlNodeR\acontent\"\x0f\n" +
	"\rHealthRequest\"m\n" +
	"\x0eHealthResponse\x12\"\n" +
	"\fdisconnected\x18\x01 \x01(\bR\fdisconnected\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01\x12\x12\n" +
	"\x04note\x18\x03 \x01(\tR\x04noteB\b\n" +
	"\x06_error\"\f\n" +
	"\n" +
	"RunRequest\"\x85\x01\n" +
	"\vRunResponse\x12\x1a\n" +
	"\bsnapshot\x18\x01 \x01(\bR\bsnapshot\x12<\n" +
	"\n" +
	"change_set\x18\x02 \x01(\v2\x1d.mindseye.module.v1.ChangeSetR\tchangeSet\x12\x1c\n" +
	"\tcontinued\x18\x03 \x01(\bR\tcontinued\"\x11\n" +
	"\x0fDiscoverRequest\"P\n" +
	"\x10DiscoverResponse\x12<\n" +
	"\n" +
	"change_set\x18\x01 \x01(\v2\x1d.mindseye.module.v1.ChangeSetR\tchangeSet\"\x10\n" +
	"\x0eMetricsRequest\"G\n" +
	"\x0fMetricsResponse\x124\n" +
	"\ametrics\x18\x01 \x03(\v2\x1a.mindseye.module.v1.MetricR\ametrics\"K\n" +
	"\x12QuerySeriesRequest\x125\n" +
	"\x05query\x18\x01 \x01(\v2\x1f.mindseye.module.v1.SeriesQueryR\x05query\"I\n" +
	"\x13QuerySeriesResponse\x122\n" +
	"\x06series\x18\x01 \x03(\v2\x1a.mindseye.module.v1.SeriesR\x06series\"J\n" +
	"\x12QueryEventsRequest\x124\n" +
	"\x05query\x18\x01 \x01(\v2\x1e.mindseye.module.v1.EventQueryR\x05query\"H\n" +
	"\x13QueryEventsResponse\x121\n" +
	"\x06events\x18\x01 \x03(\v2\x19.mindseye.module.v1.EventR\x06events\"I\n" +
	"\x10SubscribeRequest\x125\n" +
	"\x05query\x18\x01 \x01(\v2\x1f.mindseye.module.v1.SeriesQueryR\x05query\"G\n" +
	"\x11SubscribeResponse\x122\n" +
	"\x06series\x18\x01 \x03(\v2\x1a.mindseye.module.v1.SeriesR\x06series\"9\n" +
	"\rSearchRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"$\n" +
	"\x0eSearchResponse\x12\x12\n" +
	"\x04refs\x18\x01 \x03(\tR\x04refs\"\xfe\x01\n" +
	"\tChangeSet\x12\x18\n" +
	"\aremoves\x18\x01 \x03(\tR\aremoves\x12>\n" +
	"\fremove_edges\x18\x02 \x03(\v2\x1b.mindseye.module.v1.EdgeKeyR\vremoveEdges\x124\n" +
	"\aupserts\x18\x03 \x03(\v2\x1a.mindseye.module.v1.EntityR\aupserts\x12.\n" +
	"\x05edges\x18\x04 \x03(\v2\x18.mindseye.module.v1.EdgeR\x05edges\x121\n" +
	"\x06events\x18\x05 \x03(\v2\x19.mindseye.module.v1.EventR\x06events\"\xf3\x02\n" +
	"\x06Entity\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12;\n" +
	"\x05attrs\x18\x04 \x03(\v2%.mindseye.module.v1.Entity.AttrsEntryR\x05attrs\x127\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1f.mindseye.module.v1.StatusLevelR\x06status\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x12\x16\n" +
	"\x06source\x18\b \x01(\tR\x06source\x12\x17\n" +
	"\x04seen\x18\t \x01(\x12H\x00R\x04seen\x88\x01\x01\x1aS\n" +
	"\n" +
	"AttrsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.mindseye.module.v1.ValueR\x05value:\x028\x01B\a\n" +
	"\x05_seen\"?\n" +
	"\aEdgeKey\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x10\n" +
	"\x03rel\x18\x03 \x01(\tR\x03rel\"\xfc\x01\n" +
	"\x04Edge\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x10\n" +
	"\x03rel\x18\x03 \x01(\tR\x03rel\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\x01R\x06weight\x129\n" +
	"\x05attrs\x18\x05 \x03(\v2#.mindseye.module.v1.Edge.AttrsEntryR\x05attrs\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\x1aS\n" +
	"\n" +
	"AttrsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.mindseye.module.v1.ValueR\x05value:\x028\x01\"\xe0\x02\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06entity\x18\x02 \x01(\tR\x06entity\x12\x13\n" +
	"\x02at\x18\x03 \x01(\x12H\x00R\x02at\x88\x01\x01\x128\n" +
	"\bseverity\x18\x04 \x01(\x0e2\x1c.mindseye.module.v1.SeverityR\bseverity\x12\x12\n" +
	"\x04kind\x18\x05 \x01(\tR\x04kind\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x12=\n" +
	"\x06fields\x18\a \x03(\v2%.mindseye.module.v1.Event.FieldsEntryR\x06fields\x12\x16\n" +
	"\x06source\x18\b \x01(\tR\x06source\x1aT\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.mindseye.module.v1.ValueR\x05value:\x028\x01B\x05\n" +
	"\x03_at\"\xdc\x01\n" +
	"\x05Value\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12#\n" +
	"\fnumber_value\x18\x02 \x01(\x01H\x00R\vnumberValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x03 \x01(\bH\x00R\tboolValue\x12\x1f\n" +
	"\n" +
	"time_value\x18\x04 \x01(\x12H\x00R\ttimeValue\x12>\n" +
	"\n" +
	"list_value\x18\x05 \x01(\v2\x1d.mindseye.module.v1.ValueListH\x00R\tlistValueB\a\n" +
	"\x05value\">\n" +
	"\tValueList\x121\n" +
	"\x06values\x18\x01 \x03(\v2\x19.mindseye.module.v1.ValueR\x06values\"\x96\x01\n" +
	"\x06Metric\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04unit\x18\x02 \x01(\tR\x04unit\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05kinds\x18\x04 \x03(\tR\x05kinds\x12\x16\n" +
	"\x06native\x18\x05 \x01(\tR\x06native\x12\x14\n" +
	"\x05extra\x18\x06 \x01(\bR\x05extra\"J\n" +
	"\n" +
	"TimeWindow\x12\x17\n" +
	"\x04from\x18\x01 \x01(\x12H\x00R\x04from\x88\x01\x01\x12\x13\n" +
	"\x02to\x18\x02 \x01(\x12H\x01R\x02to\x88\x01\x01B\a\n" +
	"\x05_fromB\x05\n" +
	"\x03_to\"\x8e\x02\n" +
	"\vSeriesQuery\x12\x1a\n" +
	"\bentities\x18\x01 \x03(\tR\bentities\x122\n" +
	"\x06filter\x18\x02 \x01(\v2\x1a.mindseye.module.v1.FilterR\x06filter\x12\x18\n" +
	"\ametrics\x18\x03 \x03(\tR\ametrics\x126\n" +
	"\x06window\x18\x04 \x01(\v2\x1e.mindseye.module.v1.TimeWindowR\x06window\x12\x12\n" +
	"\x04step\x18\x05 \x01(\x03R\x04step\x121\n" +
	"\x03agg\x18\x06 \x01(\x0e2\x1f.mindseye.module.v1.AggregationR\x03agg\x12\x16\n" +
	"\x06native\x18\a \x01(\tR\x06native\"\xf1\x01\n" +
	"\x06Filter\x12\x14\n" +
	"\x05kinds\x18\x01 \x03(\tR\x05kinds\x12\x18\n" +
	"\asources\x18\x02 \x03(\tR\asources\x12;\n" +
	"\bstatuses\x18\x03 \x03(\x0e2\x1f.mindseye.module.v1.StatusLevelR\bstatuses\x12\x18\n" +
	"\ametrics\x18\x04 \x03(\tR\ametrics\x12\x17\n" +
	"\asame_as\x18\x05 \x03(\tR\x06sameAs\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x123\n" +
	"\x05attrs\x18\a \x03(\v2\x1d.mindseye.module.v1.PredicateR\x05attrs\"C\n" +
	"\tPredicate\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x0e\n" +
	"\x02op\x18\x02 \x01(\tR\x02op\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\";\n" +
	"\tSeriesRef\x12\x16\n" +
	"\x06entity\x18\x01 \x01(\tR\x06entity\x12\x16\n" +
	"\x06metric\x18\x02 \x01(\tR\x06metric\"{\n" +
	"\x06Series\x12/\n" +
	"\x03ref\x18\x01 \x01(\v2\x1d.mindseye.module.v1.SeriesRefR\x03ref\x12\x12\n" +
	"\x04unit\x18\x02 \x01(\tR\x04unit\x12\x14\n" +
	"\x05times\x18\x03 \x03(\x12R\x05times\x12\x16\n" +
	"\x06values\x18\x04 \x03(\x01R\x06values\"\xcd\x01\n" +
	"\n" +
	"EventQuery\x12\x1a\n" +
	"\bentities\x18\x01 \x03(\tR\bentities\x126\n" +
	"\x06window\x18\x02 \x01(\v2\x1e.mindseye.module.v1.TimeWindowR\x06window\x12?\n" +
	"\fmin_severity\x18\x03 \x01(\x0e2\x1c.mindseye.module.v1.SeverityR\vminSeverity\x12\x14\n" +
	"\x05kinds\x18\x04 \x03(\tR\x05kinds\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit*\x81\x01\n" +
	"\vStatusLevel\x12\x18\n" +
	"\x14STATUS_LEVEL_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fSTATUS_LEVEL_OK\x10\x01\x12\x15\n" +
	"\x11STATUS_LEVEL_WARN\x10\x02\x12\x15\n" +
	"\x11STATUS_LEVEL_CRIT\x10\x03\x12\x15\n" +
	"\x11STATUS_LEVEL_DOWN\x10\x04*o\n" +
	"\bSeverity\x12\x12\n" +
	"\x0eSEVERITY_DEBUG\x10\x00\x12\x11\n" +
	"\rSEVERITY_INFO\x10\x01\x12\x11\n" +
	"\rSEVERITY_WARN\x10\x02\x12\x12\n" +
	"\x0eSEVERITY_ERROR\x10\x03\x12\x15\n" +
	"\x11SEVERITY_CRITICAL\x10\x04*\x8c\x01\n" +
	"\vAggregation\x12\x14\n" +
	"\x10AGGREGATION_NONE\x10\x00\x12\x13\n" +
	"\x0fAGGREGATION_AVG\x10\x01\x12\x13\n" +
	"\x0fAGGREGATION_MAX\x10\x02\x12\x13\n" +
	"\x0fAGGREGATION_MIN\x10\x03\x12\x13\n" +
	"\x0fAGGREGATION_SUM\x10\x04\x12\x13\n" +
	"\x0fAGGREGATION_P95\x10\x052\xe7\x06\n" +
	"\rModuleService\x12I\n" +
	"\x04Info\x12\x1f.mindseye.module.v1.InfoRequest\x1a .mindseye.module.v1.InfoResponse\x12X\n" +
	"\tConfigure\x12$.mindseye.module.v1.ConfigureRequest\x1a%.mindseye.module.v1.ConfigureResponse\x12O\n" +
	"\x06Health\x12!.mindseye.module.v1.HealthRequest\x1a\".mindseye.module.v1.HealthResponse\x12H\n" +
	"\x03Run\x12\x1e.mindseye.module.v1.RunRequest\x1a\x1f.mindseye.module.v1.RunResponse0\x01\x12U\n" +
	"\bDiscover\x12#.mindseye.module.v1.DiscoverRequest\x1a$.mindseye.module.v1.DiscoverResponse\x12R\n" +
	"\aMetrics\x12\".mindseye.module.v1.MetricsRequest\x1a#.mindseye.module.v1.MetricsResponse\x12^\n" +
	"\vQuerySeries\x12&.mindseye.module.v1.QuerySeriesRequest\x1a'.mindseye.module.v1.QuerySeriesResponse\x12^\n" +
	"\vQueryEvents\x12&.mindseye.module.v1.QueryEventsRequest\x1a'.mindseye.module.v1.QueryEventsResponse\x12Z\n" +
	"\tSubscribe\x12$.mindseye.module.v1.SubscribeRequest\x1a%.mindseye.module.v1.SubscribeResponse0\x01\x12O\n" +
	"\x06Search\x12!.mindseye.module.v1.SearchRequest\x1a\".mindseye.module.v1.SearchResponseB!Z\x1fmindseye/pkg/sdk/proto/modulev1b\x06proto3"

var (
	file_mindseye_module_v1_module_proto_rawDescOnce sync.Once
	file_mindseye_module_v1_module_proto_rawDescData []byte
)

func file_mindseye_module_v1_module_proto_rawDescGZIP() []byte {
	file_mindseye_module_v1_module_proto_rawDescOnce.Do(func() {
		file_mindseye_module_v1_module_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mindseye_module_v1_module_proto_rawDesc), len(file_mindseye_module_v1_module_proto_rawDesc)))
	})
	return file_mindseye_module_v1_module_proto_rawDescData
}

var file_mindseye_module_v1_module_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_mindseye_module_v1_module_proto_msgTypes = make([]protoimpl.MessageInfo, 40)
var file_mindseye_module_v1_module_proto_goTypes = []any{
	(StatusLevel)(0),            // 0: mindseye.module.v1.StatusLevel
	(Severity)(0),               // 1: mindseye.module.v1.Severity
	(Aggregation)(0),            // 2: mindseye.module.v1.Aggregation
	(*Version)(nil),             // 3: mindseye.module.v1.Version
	(*InfoRequest)(nil),         // 4: mindseye.module.v1.InfoRequest
	(*InfoResponse)(nil),        // 5: mindseye.module.v1.InfoResponse
	(*ConfigureRequest)(nil),    // 6: mindseye.module.v1.ConfigureRequest
	(*ConfigureResponse)(nil),   // 7: mindseye.module.v1.ConfigureResponse
	(*YamlNode)(nil),            // 8: mindseye.module.v1.YamlNode
	(*HealthRequest)(nil),       // 9: mindseye.module.v1.HealthRequest
	(*HealthResponse)(nil),      // 10: mindseye.module.v1.HealthResponse
	(*RunRequest)(nil),          // 11: mindseye.module.v1.RunRequest
	(*RunResponse)(nil),         // 12: mindseye.module.v1.RunResponse
	(*DiscoverRequest)(nil),     // 13: mindseye.module.v1.DiscoverRequest
	(*DiscoverResponse)(nil),    // 14: mindseye.module.v1.DiscoverResponse
	(*MetricsRequest)(nil),      // 15: mindseye.module.v1.MetricsRequest
	(*MetricsResponse)(nil),     // 16: mindseye.module.v1.MetricsResponse
	(*QuerySeriesRequest)(nil),  // 17: mindseye.module.v1.QuerySeriesRequest
	(*QuerySeriesResponse)(nil), // 18: mindseye.module.v1.QuerySeriesResponse
	(*QueryEventsRequest)(nil),  // 19: mindseye.module.v1.QueryEventsRequest
	(*QueryEventsResponse)(nil), // 20: mindseye.module.v1.QueryEventsResponse
	(*SubscribeRequest)(nil),    // 21: mindseye.module.v1.SubscribeRequest
	(*SubscribeResponse)(nil),   // 22: mindseye.module.v1.SubscribeResponse
	(*SearchRequest)(nil),       // 23: mindseye.module.v1.SearchRequest
	(*SearchResponse)(nil),      // 24: mindseye.module.v1.SearchResponse
	(*ChangeSet)(nil),           // 25: mindseye.module.v1.ChangeSet
	(*Entity)(nil),              // 26: mindseye.module.v1.Entity
	(*EdgeKey)(nil),             // 27: mindseye.module.v1.EdgeKey
	(*Edge)(nil),                // 28: mindseye.module.v1.Edge
	(*Event)(nil),               // 29: mindseye.module.v1.Event
	(*Value)(nil),               // 30: mindseye.module.v1.Value
	(*ValueList)(nil),           // 31: mindseye.module.v1.ValueList
	(*Metric)(nil),              // 32: mindseye.module.v1.Metric
	(*TimeWindow)(nil),          // 33: mindseye.module.v1.TimeWindow
	(*SeriesQuery)(nil),         // 34: mindseye.module.v1.SeriesQuery
	(*Filter)(nil),              // 35: mindseye.module.v1.Filter
	(*Predicate)(nil),           // 36: mindseye.module.v1.Predicate
	(*SeriesRef)(nil),           // 37: mindseye.module.v1.SeriesRef
	(*Series)(nil),              // 38: mindseye.module.v1.Series
	(*EventQuery)(nil),          // 39: mindseye.module.v1.EventQuery
	nil,                         // 40: mindseye.module.v1.Entity.AttrsEntry
	nil,                         // 41: mindseye.module.v1.Edge.AttrsEntry
	nil,                         // 42: mindseye.module.v1.Event.FieldsEntry
}
var file_mindseye_module_v1_module_proto_depIdxs = []int32{
	3,  // 0: mindseye.module.v1.InfoRequest.host:type_name -> mindseye.module.v1.Version
	3,  // 1: mindseye.module.v1.InfoResponse.module:type_name -> mindseye.module.v1.Version
	8,  // 2: mindseye.module.v1.ConfigureRequest.options:type_name -> mindseye.module.v1.YamlNode
	8,  // 3: mindseye.module.v1.YamlNode.content:type_name -> mindseye.module.v1.YamlNode
	25, // 4: mindseye.module.v1.RunResponse.change_set:type_name -> mindseye.module.v1.ChangeSet
	25, // 5: mindseye.module.v1.DiscoverResponse.change_set:type_name -> mindseye.module.v1.ChangeSet
	32, // 6: mindseye.module.v1.MetricsResponse.metrics:type_name -> mindseye.module.v1.Metric
	34, // 7: mindseye.module.v1.QuerySeriesRequest.query:type_name -> mindseye.module.v1.SeriesQuery
	38, // 8: mindseye.module.v1.QuerySeriesResponse.series:type_name -> mindseye.module.v1.Series
	39, // 9: mindseye.module.v1.QueryEventsRequest.query:type_name -> mindseye.module.v1.EventQuery
	29, // 10: mindseye.module.v1.QueryEventsResponse.events:type_name -> mindseye.module.v1.Event
	34, // 11: mindseye.module.v1.SubscribeRequest.query:type_name -> mindseye.module.v1.SeriesQuery
	38, // 12: mindseye.module.v1.SubscribeResponse.series:type_name -> mindseye.module.v1.Series
	27, // 13: mindseye.module.v1.ChangeSet.remove_edges:type_name -> mindseye.module.v1.EdgeKey
	26, // 14: mindseye.module.v1.ChangeSet.upserts:type_name -> mindseye.module.v1.Entity
	28, // 15: mindseye.module.v1.ChangeSet.edges:type_name -> mindseye.module.v1.Edge
	29, // 16: mindseye.module.v1.ChangeSet.events:type_name -> mindseye.module.v1.Event
	40, // 17: mindseye.module.v1.Entity.attrs:type_name -> mindseye.module.v1.Entity.AttrsEntry
	0,  // 18: mindseye.module.v1.Entity.status:type_name -> mindseye.module.v1.StatusLevel
	41, // 19: mindseye.module.v1.Edge.attrs:type_name -> mindseye.module.v1.Edge.AttrsEntry
	1,  // 20: mindseye.module.v1.Event.severity:type_name -> mindseye.module.v1.Severity
	42, // 21: mindseye.module.v1.Event.fields:type_name -> mindseye.module.v1.Event.FieldsEntry
	31, // 22: mindseye.module.v1.Value.list_value:type_name -> mindseye.module.v1.ValueList
	30, // 23: mindseye.module.v1.ValueList.values:type_name -> mindseye.module.v1.Value
	35, // 24: mindseye.module.v1.SeriesQuery.filter:type_name -> mindseye.module.v1.Filter
	33, // 25: mindseye.module.v1.SeriesQuery.window:type_name -> mindseye.module.v1.TimeWindow
	2,  // 26: mindseye.module.v1.SeriesQuery.agg:type_name -> mindseye.module.v1.Aggregation
	0,  // 27: mindseye.module.v1.Filter.statuses:type_name -> mindseye.module.v1.StatusLevel
	36, // 28: mindseye.module.v1.Filter.attrs:type_name -> mindseye.module.v1.Predicate
	37, // 29: mindseye.module.v1.Series.ref:type_name -> mindseye.module.v1.SeriesRef
	33, // 30: mindseye.module.v1.EventQuery.window:type_name -> mindseye.module.v1.TimeWindow
	1,  // 31: mindseye.module.v1.EventQuery.min_severity:type_name -> mindseye.module.v1.Severity
	30, // 32: mindseye.module.v1.Entity.AttrsEntry.value:type_name -> mindseye.module.v1.Value
	30, // 33: mindseye.module.v1.Edge.AttrsEntry.value:type_name -> mindseye.module.v1.Value
	30, // 34: mindseye.module.v1.Event.FieldsEntry.value:type_name -> mindseye.module.v1.Value
	4,  // 35: mindseye.module.v1.ModuleService.Info:input_type -> mindseye.module.v1.InfoRequest
	6,  // 36: mindseye.module.v1.ModuleService.Configure:input_type -> mindseye.module.v1.ConfigureRequest
	9,  // 37: mindseye.module.v1.ModuleService.Health:input_type -> mindseye.module.v1.HealthRequest
	11, // 38: mindseye.module.v1.ModuleService.Run:input_type -> mindseye.module.v1.RunRequest
	13, // 39: mindseye.module.v1.ModuleService.Discover:input_type -> mindseye.module.v1.DiscoverRequest
	15, // 40: mindseye.module.v1.ModuleService.Metrics:input_type -> mindseye.module.v1.MetricsRequest
	17, // 41: mindseye.module.v1.ModuleService.QuerySeries:input_type -> mindseye.module.v1.QuerySeriesRequest
	19, // 42: mindseye.module.v1.ModuleService.QueryEvents:input_type -> mindseye.module.v1.QueryEventsRequest
	21, // 43: mindseye.module.v1.ModuleService.Subscribe:input_type -> mindseye.module.v1.SubscribeRequest
	23, // 44: mindseye.module.v1.ModuleService.Search:input_type -> mindseye.module.v1.SearchRequest
	5,  // 45: mindseye.module.v1.ModuleService.Info:output_type -> mindseye.module.v1.InfoResponse
	7,  // 46: mindseye.module.v1.ModuleService.Configure:output_type -> mindseye.module.v1.ConfigureResponse
	10, // 47: mindseye.module.v1.ModuleService.Health:output_type -> mindseye.module.v1.HealthResponse
	12, // 48: mindseye.module.v1.ModuleService.Run:output_type -> mindseye.module.v1.RunResponse
	14, // 49: mindseye.module.v1.ModuleService.Discover:output_type -> mindseye.module.v1.DiscoverResponse
	16, // 50: mindseye.module.v1.ModuleService.Metrics:output_type -> mindseye.module.v1.MetricsResponse
	18, // 51: mindseye.module.v1.ModuleService.QuerySeries:output_type -> mindseye.module.v1.QuerySeriesResponse
	20, // 52: mindseye.module.v1.ModuleService.QueryEvents:output_type -> mindseye.module.v1.QueryEventsResponse
	22, // 53: mindseye.module.v1.ModuleService.Subscribe:output_type -> mindseye.module.v1.SubscribeResponse
	24, // 54: mindseye.module.v1.ModuleService.Search:output_type -> mindseye.module.v1.SearchResponse
	45, // [45:55] is the sub-list for method output_type
	35, // [35:45] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	35, // [35:35] is the sub-list for extension extendee
	0,  // [0:35] is the sub-list for field type_name
}

func init() { file_mindseye_module_v1_module_proto_init() }
func file_mindseye_module_v1_module_proto_init() {
	if File_mindseye_module_v1_module_proto != nil {
		return
	}
	file_mindseye_module_v1_module_proto_msgTypes[7].OneofWrappers = []any{}
	file_mindseye_module_v1_module_proto_msgTypes[23].OneofWrappers = []any{}
	file_mindseye_module_v1_module_proto_msgTypes[26].OneofWrappers = []any{}
	file_mindseye_module_v1_module_proto_msgTypes[27].OneofWrappers = []any{
		(*Value_StringValue)(nil),
		(*Value_NumberValue)(nil),
		(*Value_BoolValue)(nil),
		(*Value_TimeValue)(nil),
		(*Value_ListValue)(nil),
	}
	file_mindseye_module_v1_module_proto_msgTypes[30].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mindseye_module_v1_module_proto_rawDesc), len(file_mindseye_module_v1_module_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   40,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mindseye_module_v1_module_proto_goTypes,
		DependencyIndexes: file_mindseye_module_v1_module_proto_depIdxs,
		EnumInfos:         file_mindseye_module_v1_module_proto_enumTypes,
		MessageInfos:      file_mindseye_module_v1_module_proto_msgTypes,
	}.Build()
	File_mindseye_module_v1_module_proto = out.File
	file_mindseye_module_v1_module_proto_goTypes = nil
	file_mindseye_module_v1_module_proto_depIdxs = nil
}
